name: deployment_workflow

env:
  URL_CHECKER_TIMEOUT: 60  # Reasonable timeout value in seconds

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE.txt'
      - 'src/posts/contribute/contribute.md'
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          all_but_latest: true

  test:
    needs: cancel-previous-runs
    runs-on: ubuntu-latest
    concurrency:
      group: deployment_workflow
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint:all

      - name: Run scripts in script/ folder
        run: |
          for script in script/*.js; do
            if [ -f "$script" ] && [ -x "$script" ]; then
              echo "Running $script"
              "$script" || exit 1
            fi
          done

      - name: Run URL checker
        run: node script/url-checker.js
        env:
          URL_CHECKER_TIMEOUT: ${{ env.URL_CHECKER_TIMEOUT }}
