name: deployment_workflow

env:
  URL_CHECKER_TIMEOUT: 60  # Reasonable timeout value in seconds
  PATH_PREFIX: "/${{ github.event.repository.name }}/"  # Format PATH_PREFIX

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE.txt'
      - 'src/posts/contribute/contribute.md'
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          all_but_latest: true

  test:
    needs: cancel-previous-runs
    runs-on: ubuntu-latest
    concurrency:
      group: deployment_workflow
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint:all

      - name: Run scripts in script/ folder
        run: |
          set -e
          for script in script/*.js; do
            if [ -f "$script" ] && [ -x "$script" ]; then
              echo "Running $script"
              node "$script"
            fi
          done
        env:
          URL_CHECKER_TIMEOUT: ${{ env.URL_CHECKER_TIMEOUT }}

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Verify test job success
        run: echo "Test job succeeded."

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5.0.0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Set PATH_PREFIX for Eleventy
        run: |
          echo "PATH_PREFIX=${{ env.PATH_PREFIX }}"
          echo "PATH_PREFIX=${{ env.PATH_PREFIX }}" >> $GITHUB_ENV

      - name: Build static pages with Eleventy (Production)
        run: npm run eleventy:prod

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site
